name: Docker Build and Push - SWGOH Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PAT }} | docker login --username morgs27 --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t morgs27/swgoh-website:latest .
          docker push morgs27/swgoh-website:latest
